studySpec:
  metrics:
  - metricId: accuracy
    goal: MAXIMIZE
  parameters:
  - parameterId: learning_rate
    doubleValueSpec:
      minValue: 0.01
      maxValue: 1
  - parameterId: momentum
    doubleValueSpec:
      minValue: 0
      maxValue: 1
  - parameterId: num_neurons
    discreteValueSpec:
      values: 64
trialJobSpec:
  workerPoolSpecs:
    - machineSpec:
        machineType: n1-standard-4
      replicaCount: 1
      containerSpec:
        imageUri: gcr.io/projek/tes:clauserun