workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-8
  replicaCount: 1
  diskSpec:
      bootDiskType: pd-ssd
      bootDiskSizeGb: 100
  containerSpec:
    imageUri: gcr.io/cok/zepir:runner