sed -i 's/cok/'$project'/' arti3
sed -i 's/cok/'$project'/' arti3
sed -i 's/cok/'$project'/' arti3
sed -i 's/cok/'$project'/' arti3
sed -i 's/cok/'$project'/' arti3
sed -i 's/cok/'$project'/' arti3
sed -i 's/cok/'$project'/' arti3
sed -i 's/cok/'$project'/' arti3
sed -i 's/cok/'$project'/' arti3
sed -i 's/cok/'$project'/' arti3
sed -i 's/cok/'$project'/' arti3
sed -i 's/cok/'$project'/' arti3
sed -i 's/cok/'$project'/' arti3
sed -i 's/cok/'$project'/' arti3
sed -i 's/cok/'$project'/' arti3
sed -i 's/cok/'$project'/' arti3
sed -i 's/cok/'$project'/' arti4
sed -i 's/cok/'$project'/' arti4
sed -i 's/cok/'$project'/' arti4
sed -i 's/cok/'$project'/' arti4
sed -i 's/cok/'$project'/' arti4
sed -i 's/cok/'$project'/' arti4
sed -i 's/cok/'$project'/' arti4
sed -i 's/cok/'$project'/' arti4
sed -i 's/cok/'$project'/' arti4
sed -i 's/cok/'$project'/' arti4
sed -i 's/cok/'$project'/' arti4
sed -i 's/cok/'$project'/' arti4
sed -i 's/cok/'$project'/' arti4
sed -i 's/cok/'$project'/' arti4
sed -i 's/cok/'$project'/' arti4
sed -i 's/cok/'$project'/' arti4